lora_r: 8
lora_index: true
name: lora-cifar10-linear
pretrained_feature_extractor: /home/model-server/code/adv/trained_models/byol/0/byol-cifar10-0-ep=999.ckpt
backbone:
  name: resnet18
  kwargs: {}
pretrain_method: byol
data:
  dataset: cifar10
  train_path: /home/model-server/code/adv//datasets/cifar-10
  val_path: /home/model-server/code/adv//datasets/cifar-10
  format: image_folder
  num_workers: 4
  data_fraction: 0.1
  fraction: -1
  augmentations:
    crop_size: 224
    mean:
    - 0.485
    - 0.456
    - 0.406
    std:
    - 0.229
    - 0.224
    - 0.225
  num_classes: 10
optimizer:
  name: sgd
  batch_size: 256
  lr: 0.1
  weight_decay: 0
  kwargs:
    momentum: 0.9
  exclude_bias_n_norm_wd: false
  layer_decay: 0.0
scheduler:
  name: step
  lr_decay_steps:
  - 10
  - 20
  min_lr: 0.0
  warmup_start_lr: 3.0e-05
  warmup_epochs: 10
  interval: step
checkpoint:
  enabled: true
  dir: trained_models
  frequency: 1
  keep_prev: false
auto_resume:
  enabled: false
  max_hours: 36
finetune: false
max_epochs: 25
devices:
- 0
sync_batchnorm: true
accelerator: gpu
strategy: ddp
precision: 16
wandb:
  enabled: false
  entity: null
  project: solo-learn
  offline: false
dali:
  device: gpu
seed: 5
resume_from_checkpoint: null
auto_augment: false
label_smoothing: 0.0
mixup: 0.0
cutmix: 0.0
num_nodes: 1
accumulate_grad_batches: 1
performance:
  disable_channel_last: false
